name       : taskwarrior
version    : 2.6.2
release    : 8
source     :
    - git|https://github.com/GothenburgBitFactory/taskwarrior : v2.6.2
license    : MIT
component  : office.notes
summary    : Command-Line Task Management
description: |
    Taskwarrior is Free and Open Source Software that manages your TODO list from the command line. It is flexible, fast, and unobtrusive. It does its job then gets out of your way.
builddeps  :
    - pkgconfig(gnutls)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test
